.TH "main.c" 3 "Sun Oct 31 2021" "Onegin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- main  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'onegin\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
main 


.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin from the source code\&.
