.TH "onegin.h" 3 "Sun Oct 31 2021" "Onegin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
onegin.h \- functions prototypes  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmystrcmp\fP (const char *first, const char *second)"
.br
.RI "сравнивает данные функции строчки "
.ti -1c
.RI "int \fBcompar\fP (const void *pl1, const void *pl2)"
.br
.ti -1c
.RI "size_t \fBcount_lines\fP (FILE *file)"
.br
.RI "count lines of given file "
.in -1c
.SH "Detailed Description"
.PP 
functions prototypes 


.SH "Function Documentation"
.PP 
.SS "size_t count_lines (FILE * file)"

.PP
count lines of given file 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP given file 
.RE
.PP

.SS "int mystrcmp (const char * first, const char * second)"

.PP
сравнивает данные функции строчки 
.PP
\fBParameters\fP
.RS 4
\fIfirst\fP first given string 
.br
\fIsecond\fP second given string 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin from the source code\&.
